/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_giang;

import BTL_Dung.Form;
import btl_duc.QuanLyCongViecFrom;
import btl_duc.QuanLySinhVienForm;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TruongGiang
 */
public class MenuChinhForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuChinhForm
     */
    public MenuChinhForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTrangChu = new javax.swing.JButton();
        jButtonCapNhapTTGV = new javax.swing.JButton();
        jButtonSinhVien = new javax.swing.JButton();
        jButtonDanhGia = new javax.swing.JButton();
        jLabelCapNhapTTGV = new javax.swing.JLabel();
        jLabelCapNhapTTSV = new javax.swing.JLabel();
        jLabelDanhGia = new javax.swing.JLabel();
        jButtonDangXuat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/haui.png"))); // NOI18N

        jButtonCapNhapTTGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/xemGV.png"))); // NOI18N
        jButtonCapNhapTTGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhapTTGVActionPerformed(evt);
            }
        });

        jButtonSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/xemSV.png"))); // NOI18N
        jButtonSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinhVienActionPerformed(evt);
            }
        });

        jButtonDanhGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/DanhGia.png"))); // NOI18N
        jButtonDanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDanhGiaActionPerformed(evt);
            }
        });

        jLabelCapNhapTTGV.setText("Cập Nhập Thông Tin Cá Nhân");

        jLabelCapNhapTTSV.setText("Quản Lý Thông Tin Sinh Viên");

        jLabelDanhGia.setText("Đánh Giá Sinh Viên");
        jLabelDanhGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDanhGiaMouseClicked(evt);
            }
        });

        jButtonDangXuat.setText("Đăng Xuất ");
        jButtonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangXuatActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Anh/PhanCongCV.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Quản Lý Công Việc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDanhGia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCapNhapTTGV, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCapNhapTTGV)
                            .addComponent(jButtonDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jButtonSinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCapNhapTTSV)
                                    .addComponent(jLabel1))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonDangXuat)
                        .addGap(153, 153, 153)
                        .addComponent(jButtonSinhVien))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTrangChu)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonCapNhapTTGV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCapNhapTTGV)
                    .addComponent(jLabelCapNhapTTSV, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDanhGia)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabelDanhGia)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDanhGiaActionPerformed
        new DanhGiaForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDanhGiaActionPerformed

    private void jLabelDanhGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDanhGiaMouseClicked
        new DanhGiaForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelDanhGiaMouseClicked

    private void jButtonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangXuatActionPerformed
        // TODO add your handling code here:
        new DangNhapForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDangXuatActionPerformed

    private void jButtonSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinhVienActionPerformed
        // TODO add your handling code here:
        new QuanLySinhVienForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSinhVienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new QuanLyCongViecFrom().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCapNhapTTGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhapTTGVActionPerformed
        // TODO add your handling code here:
        new Form().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCapNhapTTGVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChinhForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuChinhForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCapNhapTTGV;
    private javax.swing.JButton jButtonDangXuat;
    private javax.swing.JButton jButtonDanhGia;
    private javax.swing.JButton jButtonSinhVien;
    private javax.swing.JButton jButtonTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCapNhapTTGV;
    private javax.swing.JLabel jLabelCapNhapTTSV;
    private javax.swing.JLabel jLabelDanhGia;
    // End of variables declaration//GEN-END:variables
}
