/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl_duc;
import DuLieu.SinhVien;
import DuLieu.Lop;
import DuLieu.Khoa;
import DuLieu.GiaoVien;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import btl_giang.DangNhapForm;
import btl_giang.MenuChinhForm;

public class QuanLySinhVienForm extends javax.swing.JFrame {

    private List<SinhVien> listSV= new ArrayList<>();
    private List<Lop> listLop= new ArrayList<>();
    private Connection con =null;
    private Statement stm ;
    private tableDataSinhVien tDataSinhVien;
    private Connection getConnection(){
        if(con==null){
        try {
            String url="jdbc:derby://localhost:1527/BaiTL";
            String user="Nhom4";
            String pass="123";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con=(Connection)DriverManager.getConnection(url, user, pass);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     return con;
    }
    private void getListSV(){
        con= getConnection();
        try {
            stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from SVIEN where MaLop in(select MaLop from Lop where MaGiaoVien='"+DangNhapForm.magv+"')");
            while (rs.next()) {                
                String maSV= rs.getString("MaSinhVien");
                String maLop= rs.getString("MaLop");
                float diemDG= rs.getFloat("DiemDanhGia");
                float diemTichLuy= rs.getFloat("DiemTichLuy");
                String hoTen = rs.getString("HoTen");
                String quocTich = rs.getString("QuocTich");
                String xa = rs.getString("Xa");
                String huyen = rs.getString("Quan");
                String tinh = rs.getString("Tinh");
                String soCMND = rs.getString("SoCMND");
                String sdt = rs.getString("SoDienThoai");
                String maBHYT = rs.getString("MaBHYT");
                SinhVien s = new SinhVien(maSV,new Lop(maLop),diemTichLuy,diemDG,hoTen,quocTich,xa,
                huyen,tinh,soCMND,sdt,maBHYT);
                listSV.add(s);
            }
        } catch (Exception e) {
            System.out.println("Lỗi "+ e.getMessage());
        }
    }
    private void getListLop(){
        con= getConnection();
        try {
            stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from LOP where MaGiaoVien='"+DangNhapForm.magv+"'");
            while (rs.next()) {  
                jComboBox1.addItem(rs.getString("TenLop"));
                String maLop = rs.getString("MaLop");
                String tenLop =rs.getString("TenLop");
                String maGV= rs.getString("MaGiaoVien");
                String maKhoa =rs.getString("MaKhoa");
                Lop l = new Lop(maLop,tenLop,new Khoa(maKhoa),new GiaoVien(maGV));
                listLop.add(l);
            }
        } catch (Exception e) {
            System.out.println("Lỗi "+e.getMessage());
        }
    }
    public QuanLySinhVienForm() {
        initComponents();
        getListLop();
        getListSV();
        loadTable(listSV);
        jTable1.getSelectionModel().addListSelectionListener((e) -> getDataRow());
        
    }
    private void getDataRow(){
        int r = jTable1.getSelectedRow();
        if(r<0){
            return;
        }
        SinhVien sinhVien=tDataSinhVien.getRowAt(r);
        jTextField1.setEnabled(false);
        jTextField1.setText(sinhVien.getMaSV());
        jTextField2.setText(sinhVien.getHoTen());
        jTextField3.setText(sinhVien.getQuocTich());
        jTextField4.setText(sinhVien.getSoCMND());
        jTextField5.setText(sinhVien.getSdt());
        jTextField6.setText(sinhVien.getLop().getMaLop());
        jTextField7.setText(sinhVien.getXa());
        jTextField8.setText(sinhVien.getHuyen());
        jTextField9.setText(sinhVien.getTinh());
        jTextField10.setText(sinhVien.getMaBHYT());
    }
    private void loadTable(List<SinhVien> list){
        tDataSinhVien= new tableDataSinhVien(list);
        jTable1.setModel(tDataSinhVien);
        jLabel15.setText(jTable1.getRowCount()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                none(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel2.setText("Mã SV:");
        jLabel2.setName(""); // NOI18N

        jLabel3.setText("Họ Tên:");

        jLabel4.setText("Quốc Tịch:");

        jLabel5.setText("Số CMND:");

        jLabel6.setText("SDT:");

        jLabel7.setText("Mã Lớp:");

        jLabel8.setText("Địa Chỉ:");

        jLabel9.setText("Xã:");

        jLabel10.setText("Huyện:");

        jLabel11.setText("Tỉnh:");

        jLabel12.setText("Mã BHYT:");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Làm Mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Xóa Trắng");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Quay Lại");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel13.setText("Tên lớp:");

        jLabel14.setText("Số Lượng:");

        jLabel15.setText("0");

        jButton7.setText("Sắp Xếp");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Họ Tên");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Điểm ĐG");

        jButton8.setText("Tìm Kiếm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Mã SV");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Họ Tên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            String maSV= jTextField1.getText();
            if(maSV.equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên","Chú Ý",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(!listSV.contains(new SinhVien(maSV))){
                JOptionPane.showMessageDialog(this, "Không tồn tại sinh viên muốn sửa!","Chú Ý",JOptionPane.WARNING_MESSAGE);
                return;
            }
            SinhVien s1 = listSV.get(listSV.indexOf(new SinhVien(maSV)));
            
            String hoTen = jTextField2.getText();
            if(hoTen.equals(""))hoTen=s1.getHoTen();
            
            String quocTich = jTextField3.getText();
            if(quocTich.equals(""))quocTich=s1.getQuocTich();
            
            String soCMND = jTextField4.getText();
            if(soCMND.equals(""))soCMND=s1.getSoCMND();
            
            String sdt = jTextField5.getText();
            if(sdt.equals(""))sdt=s1.getSdt();
            
            String maLop = jTextField6.getText();
            if(maLop.equals(""))maLop= s1.getLop().getMaLop();
            
            String xa = jTextField7.getText();
            if(xa.equals(""))xa=s1.getXa();
            
            String huyen = jTextField8.getText();
            if(huyen.equals(""))huyen=s1.getHuyen();
            
            String tinh = jTextField9.getText();
            if(tinh.equals(""))tinh=s1.getTinh();
            
            String maBHYT = jTextField10.getText();
            if(maBHYT.equals(""))maBHYT=s1.getMaBHYT();
            
            SinhVien s = new SinhVien(maSV,new Lop(maLop),hoTen,quocTich,xa,huyen, tinh,soCMND,sdt,maBHYT);
            
            con=getConnection();
            if(listLop.contains(new Lop(maLop))){
                try {
                stm=con.createStatement();
                int i=stm.executeUpdate("update SVien set HoTen='"+hoTen+"',QuocTich='"+
                        quocTich+"',SoCMND='"+soCMND+"',SoDienThoai='"+sdt+"',MaLop='"+maLop+"',Xa='"+
                        xa+"',Quan='"+huyen+"',Tinh='"+tinh+"',MaBHYT='"+maBHYT+"' where MaSinhVien='"+maSV+"'");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
                    return;
                }                   
                listSV.set(listSV.indexOf(s), s);
                loadTable(listSV);
                JOptionPane.showMessageDialog(this, "Sửa thành công.");
                jButton5ActionPerformed(evt);
                return;
            }
            JOptionPane.showMessageDialog(this, "Không có lớp này!","Chú ý",JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       new MenuChinhForm().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        jTextField1.setEnabled(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField1.requestFocus();
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadTable(listSV);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String maSV= jTextField1.getText();
            String hoTen = jTextField2.getText();
            String quocTich = jTextField3.getText();
            String soCMND = jTextField4.getText();
            String sdt = jTextField5.getText();
            String maLop = jTextField6.getText();
            String xa = jTextField7.getText();
            String huyen = jTextField8.getText();
            String tinh = jTextField9.getText();
            String maBHYT = jTextField10.getText();
            if(maSV.equals("") || hoTen.equals("") || quocTich.equals("") || soCMND.equals("") ||
                    sdt.equals("") || maLop.equals("") || xa.equals("") || huyen.equals("") ||
                    tinh.equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sinh viên!","Chú ý",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            SinhVien s = new SinhVien(maSV,new Lop(maLop),hoTen,quocTich,xa,huyen, tinh,soCMND,sdt,maBHYT);
            if(!listLop.contains(new Lop(maLop))){
                JOptionPane.showMessageDialog(this, "Không có lớp học này!","Chú ý",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(listSV.contains(s)){
                JOptionPane.showMessageDialog(this, "Sinh viên đã tổn tại!","Chú ý",JOptionPane.WARNING_MESSAGE);
                return;
            }
            con=getConnection();
                try {
                    stm=con.createStatement();
                    int r=stm.executeUpdate("insert into SVien (MaSinhVien,HoTen,QuocTich,Xa,Quan,Tinh,SoCMND,SoDienThoai,MaBHYT,MaLop) values('"+
                    maSV+"','"+hoTen+"','"+quocTich+"','"+xa+"','"+huyen+"','"+tinh+"','"+soCMND+"','"+sdt+"','"+maBHYT+"','"+maLop+"')");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                listSV.add(s);
                loadTable(listSV);
                JOptionPane.showMessageDialog(this, "Thêm thành công.");
                jButton5ActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        try {
            String MaSV= jTextField1.getText();
            if(MaSV.equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên!","Chú ý",JOptionPane.WARNING_MESSAGE);
                return;
            }
            int k= JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn xóa không?","Xác nhận xóa",JOptionPane.YES_NO_OPTION);
            if(k==JOptionPane.YES_OPTION){
                
                SinhVien s = new SinhVien(MaSV);
                if(listSV.contains(s)){
                    con=getConnection();
                    try {
                        stm=con.createStatement();
                        int r= stm.executeUpdate("delete from SVien where MaSinhVien='"+MaSV+"'");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    listSV.remove(s);
                    loadTable(listSV);
                    JOptionPane.showMessageDialog(this, "Xóa thành công.");
                    jButton5ActionPerformed(evt);
                    return;
                }
                JOptionPane.showMessageDialog(this, "Không tồn tại sinh viên muốn xóa!","Chú ý",JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       jTable1.clearSelection();
       String tenLop = evt.getItem().toString();
       List<SinhVien> list = new ArrayList<>();
       if(tenLop.equalsIgnoreCase("Tất cả")){
           loadTable(listSV);
       }
       else{
           con= getConnection();
        try {
            list.clear();
            stm=con.createStatement();
            ResultSet rs= stm.executeQuery("select * from SVIEN inner join Lop on SVien.MaLop=Lop.MaLop where TenLop='"+tenLop+"'");
            while (rs.next()) {                
                String maSV= rs.getString("MaSinhVien");
                String maLop= rs.getString("MaLop");
                float diemDG= rs.getFloat("DiemDanhGia");
                float diemTichLuy= rs.getFloat("DiemTichLuy");
                String hoTen = rs.getString("HoTen");
                String quocTich = rs.getString("QuocTich");
                String xa = rs.getString("Xa");
                String huyen = rs.getString("Quan");
                String tinh = rs.getString("Tinh");
                String soCMND = rs.getString("SoCMND");
                String sdt = rs.getString("SoDienThoai");
                String maBHYT = rs.getString("MaBHYT");
                SinhVien s = new SinhVien(maSV,new Lop(maLop),diemTichLuy,diemDG,hoTen,quocTich,xa,
                huyen,tinh,soCMND,sdt,maBHYT);
                list.add(s);
            }
            loadTable(list);
        } catch (Exception e) {
            System.out.println("Lỗi "+ e.getMessage());
        }
       } 
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none

    }//GEN-LAST:event_none

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       List<SinhVien> list = tDataSinhVien.getList();
        try {
            if(jRadioButton1.isSelected()){
               Comparator<SinhVien> c= new Comparator<SinhVien>() {
                   @Override
                   public int compare(SinhVien o1, SinhVien o2) {
                       return o1.getHoTen().compareToIgnoreCase(o2.getHoTen());
                   }
               };
                Collections.sort(list,c);
                loadTable(list);     
               }
            else{
                Comparator<SinhVien> c1= new Comparator<SinhVien>() {
                    @Override
                    public int compare(SinhVien o1, SinhVien o2) {
                       return Float.compare(o1.getDiemDG(), o2.getDiemDG());
                    }
                };
                Collections.sort(list,c1);
                loadTable(list);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       List<SinhVien> list = new ArrayList<>();
       List<SinhVien> listFind = tDataSinhVien.getList();
        try {
            if(jRadioButton3.isSelected()){
                if(jTextField1.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sinh viên để tìm kiếm!","Chú Ý",JOptionPane.WARNING_MESSAGE);
                    return;  
                }
                String maSV = jTextField1.getText();
                for(SinhVien sinhVien:listFind){
                    if(maSV.equals(sinhVien.getMaSV())){
                        list.add(sinhVien);
                    }
                }
                loadTable(list);
                JOptionPane.showMessageDialog(this, "Có "+list.size()+" kết quả trùng khớp.");
                return;
            }
            if(jRadioButton4.isSelected()){
                if(jTextField2.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập họ tên để tìm kiếm!","Chú Ý",JOptionPane.WARNING_MESSAGE);
                    return;  
                }
                String hoTen = jTextField2.getText();
                for(SinhVien sinhVien:listFind){
                    if(hoTen.equals(sinhVien.getHoTen())){
                        list.add(sinhVien);
                    }
                }
                loadTable(list);
                JOptionPane.showMessageDialog(this, "Có "+list.size()+" kết quả trùng khớp.");
                return;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi "+e.getMessage(),"Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
